services:
  rails:
    image: chatwoot/chatwoot:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    volumes:
      - ./data/storage:/app/storage
    networks:
      - 1panel-network
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - POSTGRES_HOST=${PANEL_DB_HOST}
      - POSTGRES_PORT=${PANEL_DB_PORT}
      - POSTGRES_USERNAME=${PANEL_DB_USER}
      - POSTGRES_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - POSTGRES_DATABASE=${PANEL_DB_NAME}
      - REDIS_URL=redis://default:${PANEL_REDIS_ROOT_PASSWORD}@${PANEL_REDIS_HOST}:6379
      - REDIS_PASSWORD=${PANEL_REDIS_ROOT_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - FORCE_SSL=false
    entrypoint: docker/entrypoints/rails.sh
    command:
      - bundle
      - exec
      - rails
      - s
      - -p
      - "3000"
      - -b
      - 0.0.0.0
    labels:
      createdBy: Apps
  sidekiq:
    image: chatwoot/chatwoot:latest
    container_name: ${CONTAINER_NAME}-Sidekiq
    restart: always
    volumes:
      - ./data/storage:/app/storage
    networks:
      - 1panel-network
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - POSTGRES_HOST=${PANEL_DB_HOST}
      - POSTGRES_PORT=${PANEL_DB_PORT}
      - POSTGRES_USERNAME=${PANEL_DB_USER}
      - POSTGRES_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - POSTGRES_DATABASE=${PANEL_DB_NAME}
      - REDIS_URL=redis://default:${PANEL_REDIS_ROOT_PASSWORD}@${PANEL_REDIS_HOST}:6379
      - REDIS_PASSWORD=${PANEL_REDIS_ROOT_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - FORCE_SSL=false
    command:
      - bundle
      - exec
      - sidekiq
      - -C
      - config/sidekiq.yml
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
