services:
  web:
    image: dolibarr/dolibarr:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ./data/documents:/var/www/documents
      - ./data/custom:/var/www/html/custom
    networks:
      - 1panel-network
    environment:
      - DOLI_DB_HOST=${CONTAINER_NAME}-Db
      - DOLI_DB_NAME=${DOLI_DB_NAME}
      - DOLI_DB_USER=${DOLI_DB_USER}
      - DOLI_DB_PASSWORD=${DOLI_DB_PASSWORD}
      - DOLI_URL_ROOT=${DOLI_URL_ROOT}
      - DOLI_ADMIN_LOGIN=${DOLI_ADMIN_LOGIN}
      - DOLI_ADMIN_PASSWORD=${DOLI_ADMIN_PASSWORD}
      - DOLI_CRON=${DOLI_CRON}
    depends_on:
      - mariadb
    labels:
      createdBy: Apps
  mariadb:
    image: mariadb:11.4
    container_name: ${CONTAINER_NAME}-Db
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - 1panel-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DOLI_DB_PASSWORD}
      - MYSQL_DATABASE=${DOLI_DB_NAME}
      - MYSQL_USER=${DOLI_DB_USER}
      - MYSQL_PASSWORD=${DOLI_DB_PASSWORD}
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
