name: Grafana
tags:
  - 实用工具
title: 开源的可视化监控与分析平台
description: 开源的可视化监控与分析平台
additionalProperties:
  key: grafana
  name: Grafana
  tags:
    - Tool
  shortDescZh: 开源的可视化监控与分析平台
  shortDescEn: Open-source visualization and analytics platform
  description:
    en: Open-source platform for monitoring, metrics analysis and visualization
    ja: 監視、メトリクス分析、可視化のためのオープンソースプラットフォーム
    ms: Platform sumber terbuka untuk pemantauan, analisis metrik dan visualisasi
    pt-br: Plataforma de código aberto para monitoramento, análise de métricas e visualização
    ru: Платформа с открытым исходным кодом для мониторинга, анализа метрик и визуализации
    ko: 모니터링, 메트릭 분석 및 시각화를 위한 오픈소스 플랫폼
    zh-Hant: 開源的監控、指標分析與視覺化平台
    zh: 开源的可视化监控与分析平台
  type: website
  crossVersionUpdate: true
  limit: 0
  recommend: 0
  website: https://grafana.com/
  github: https://github.com/grafana/grafana
  document: https://grafana.com/docs/grafana/latest/
  architectures:
    - amd64
    - arm64
